pipeline {
    agent any
    stages {
        stage('检出') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: GIT_BUILD_REF]],
                    userRemoteConfigs: [[
                    url: GIT_REPO_URL,
                    credentialsId: CREDENTIALS_ID
                ]]])
            }
        }
        stage('安装环境') {
            steps {
                dir('./deploy/jenkins') {
                    sh 'sudo bash ./aptSource.sh'
                }

                sh 'sudo apt-get install nodejs'

                sh 'node -v'
            }
        }
    }
}