pipeline {
    agent any
    stages {
        stage('检出') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: GIT_BUILD_REF]],
                    userRemoteConfigs: [[
                    url: GIT_REPO_URL,
                    credentialsId: CREDENTIALS_ID
                ]]])
            }
        }
        stage('安装环境') {
            steps {
                dir('./deploy/jenkins') {
                    sh 'sudo bash ./aptSource.sh'
                }

                sh 'rm -rf /usr/lib/node_modules/npm/'
                dir ('/root/.cache/downloads') {
                    sh 'wget -nc "https://coding-public-generic.pkg.coding.net/public/downloads/node-linux-x64.tar.xz?version=v16.18.0" -O node-v16.18.0-linux-x64.tar.xz | true'
                    sh 'tar -xf node-v16.18.0-linux-x64.tar.xz -C /usr --strip-components 1'
                }
                sh 'node -v'
            }
        }
    }
}